### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by abyxcos** [mikejsavage/lua-fcgi#2]
src/main.c:64:28: error: use of undeclared identifier 'environ'
        for( char * const * var = environ; *var != NULL; var++ ) {

I'm seeing this pop up on FreeBSD with clang. I don't recall seeing this on Linux however. The code doesn't look right, but I can't actually figure out what it should be. Seems like it should be doing something with the lua_State * L, as I can't find environ anywhere else in the git history.

cc --version
FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
Target: x86_64-unknown-freebsd11.0
Thread model: posix
InstalledDir: /usr/bin

**Comment by mikejsavage** [comment]
`environ` is a gross part of posix. I don't know how it works but it ends up being set at startup. It's a NULL terminated array of strings (like `x=y`), holding the program's environment variables.

As a total guess, try adding `extern char **environ;` at global scope before `luafcgi_dumpenv`.

**Comment by abyxcos** [comment]
That works. Want a push?

**Comment by mikejsavage** [comment]
Since it's just a one-liner I pushed it myself. v1.1 should be up on Luarocks too.

Thanks for testing!
